from __future__ import annotations

from typing import Any

from .QtCore import QEvent

class QColor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def name(self) -> str: ...
    def isValid(self) -> bool: ...
    def setAlpha(self, alpha: int) -> None: ...
    def darker(self, factor: int = ...) -> QColor: ...
    def getRgb(self) -> tuple[int, int, int, int]: ...
    def red(self) -> int: ...
    def green(self) -> int: ...
    def blue(self) -> int: ...

class QGuiApplication:
    @staticmethod
    def primaryScreen() -> Any: ...
    @staticmethod
    def instance() -> QGuiApplication | None: ...
    @staticmethod
    def clipboard() -> Any: ...
    def palette(self) -> QPalette: ...
    def setPalette(self, palette: QPalette) -> None: ...
    def style(self) -> Any: ...
    def setStyleSheet(self, sheet: str) -> None: ...
    @staticmethod
    def processEvents(flags: int | None = None, maxtime: int | None = None) -> None: ...

class QPalette:
    Window: int
    WindowText: int
    Base: int
    AlternateBase: int
    ToolTipBase: int
    ToolTipText: int
    Text: int
    Button: int
    ButtonText: int
    BrightText: int
    Link: int
    Mid: int
    Highlight: int
    HighlightedText: int
    PlaceholderText: int
    Disabled: int
    def color(self, role: Any) -> QColor: ...
    def setColor(self, *args: Any, **kwargs: Any) -> None: ...
    class ColorRole:
        Window: int
        Base: int
        Text: int
        ButtonText: int

class QTextCharFormat:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setBackground(self, brush: Any) -> None: ...

class QTextCursor:
    End: int
    EndOfBlock: int
    KeepAnchor: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def movePosition(self, operation: int, mode: int | None = None) -> None: ...
    def insertText(self, text: str) -> None: ...

class QPixmap:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def isNull(self) -> bool: ...

class QIcon:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pixmap(self, width: int, height: int) -> QPixmap: ...

class QCloseEvent(QEvent):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QResizeEvent(QEvent):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QShowEvent(QEvent):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QPainter:
    Antialiasing: int
