from __future__ import annotations

from typing import Any

from .QtCore import QObject

class QAudioOutput(QObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QMediaPlayer(QObject):
    class PlaybackState:
        StoppedState: int

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setAudioOutput(self, output: QAudioOutput) -> None: ...
    def playbackState(self) -> int: ...
    def stop(self) -> None: ...
    def setSource(self, *args: Any, **kwargs: Any) -> None: ...
    def play(self) -> None: ...
    def position(self) -> int: ...
