from __future__ import annotations

from typing import Any, overload

from .QtCore import QEvent, QObject
from .QtGui import QColor, QTextCharFormat, QTextCursor

class QWidget(QObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def event(self, event: QEvent) -> bool: ...
    def eventFilter(self, obj: QObject, event: QEvent) -> bool: ...
    def closeEvent(self, event: QEvent) -> None: ...
    def setToolTip(self, text: str) -> None: ...
    def setVisible(self, visible: bool) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setFocus(self, reason: int | None = None) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class QApplication(QObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def setOverrideCursor(cursor: Any) -> None: ...
    @staticmethod
    def restoreOverrideCursor() -> None: ...

class QDialog(QWidget):
    Accepted: int
    Rejected: int
    def exec(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...

class QFrame(QWidget):
    StyledPanel: int

class QSplitter(QWidget):
    def addWidget(self, widget: QWidget) -> None: ...
    def setObjectName(self, name: str) -> None: ...
    def setStretchFactor(self, index: int, stretch: int) -> None: ...
    def restoreState(self, state: Any) -> None: ...
    def saveState(self) -> Any: ...
    splitterMoved: Any

class QLayout(QObject):
    SetMinimumSize: int
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def setSpacing(self, spacing: int) -> None: ...
    def addWidget(self, widget: QWidget, stretch: int | None = None) -> None: ...
    def addLayout(self, layout: QLayout, stretch: int | None = None) -> None: ...
    def addStretch(self, stretch: int = ...) -> None: ...

class QHBoxLayout(QLayout): ...
class QVBoxLayout(QLayout): ...

class QPlainTextEdit(QWidget): ...
class QLabel(QWidget): ...

class QLineEdit(QWidget):
    Password: int
    Normal: int
    class EchoMode:
        Password: int
        Normal: int

    def setEchoMode(self, mode: int) -> None: ...

class QPushButton(QWidget): ...

class QButtonGroup(QObject):
    def __init__(self, parent: QObject | None = None) -> None: ...
    def addButton(self, button: QAbstractButton, id: int | None = None) -> None: ...
    def setExclusive(self, exclusive: bool) -> None: ...
    def buttons(self) -> list[QAbstractButton]: ...
    def checkedButton(self) -> QAbstractButton | None: ...

class QComboBox(QWidget):
    NoInsert: int
    AdjustToContents: int
    def addItem(self, *args: Any, **kwargs: Any) -> None: ...

class QCheckBox(QWidget): ...
class QAbstractButton(QWidget): ...

class QToolButton(QAbstractButton):
    MenuButtonPopup: int
    clicked: Any
    def setPopupMode(self, mode: int) -> None: ...
    def setMenu(self, menu: QMenu) -> None: ...

class QRadioButton(QAbstractButton): ...

class QDialogButtonBox(QWidget):
    Ok: int
    Cancel: int
    Close: int
    ApplyRole: int
    DestructiveRole: int
    AcceptRole: int
    RejectRole: int
    def addButton(self, *args: Any, **kwargs: Any) -> Any: ...

class QMessageBox(QWidget):
    Yes: int
    No: int
    @staticmethod
    def question(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def warning(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def critical(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def information(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...

class QScrollArea(QWidget): ...
class QGroupBox(QWidget): ...

class QColorDialog(QWidget):
    @staticmethod
    def getColor(*args: Any, **kwargs: Any) -> QColor: ...

class QFormLayout(QObject):
    AllNonFixedFieldsGrow: int
    ExpandingFieldsGrow: int
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def setFieldGrowthPolicy(self, policy: int) -> None: ...
    def addRow(self, label: str | QWidget, field: QWidget) -> None: ...
    def addItem(self, item: QLayout) -> None: ...

class QGridLayout(QObject):
    def addWidget(self, *args: Any, **kwargs: Any) -> None: ...

class QHBoxLayout(QLayout):
    def addWidget(
        self,
        widget: QWidget,
        stretch: int = ...,
        alignment: int | None = None,
    ) -> None: ...
    def addLayout(self, layout: QLayout, stretch: int = ...) -> None: ...

class QVBoxLayout(QLayout):
    def addWidget(
        self,
        widget: QWidget,
        stretch: int = ...,
        alignment: int | None = None,
    ) -> None: ...
    def addLayout(self, layout: QLayout, stretch: int = ...) -> None: ...

class QSizePolicy:
    Expanding: int
    Preferred: int
    PreferredType: int
    Fixed: int
    Minimum: int

class QTableWidget(QWidget):
    SelectRows: Any
    SingleSelection: Any
    NoEditTriggers: Any
    NoSelection: Any
    @overload
    def __init__(self, parent: QWidget | None = None) -> None: ...
    @overload
    def __init__(
        self,
        rows: int,
        columns: int,
        parent: QWidget | None = None,
    ) -> None: ...
    def setSelectionBehavior(self, *args: Any, **kwargs: Any) -> None: ...
    def setSelectionMode(self, *args: Any, **kwargs: Any) -> None: ...
    def setEditTriggers(self, *args: Any, **kwargs: Any) -> None: ...
    def setRowCount(self, count: int) -> None: ...
    def setColumnCount(self, count: int) -> None: ...
    def setHorizontalHeaderLabels(self, labels: list[str]) -> None: ...
    def horizontalHeader(self) -> Any: ...
    def verticalHeader(self) -> Any: ...
    def setItem(self, row: int, column: int, item: QTableWidgetItem) -> None: ...
    def resizeColumnsToContents(self) -> None: ...

class QTableWidgetItem:
    def __init__(self, text: str) -> None: ...

class QTabWidget(QWidget): ...

class QTextEdit(QPlainTextEdit):
    class ExtraSelection:
        cursor: QTextCursor
        format: QTextCharFormat

class QTextBrowser(QWidget): ...

class QFileDialog(QWidget):
    @staticmethod
    def getSaveFileName(*args: Any, **kwargs: Any) -> tuple[str, str]: ...
    @staticmethod
    def getOpenFileName(*args: Any, **kwargs: Any) -> tuple[str, str]: ...
    @staticmethod
    def getExistingDirectory(
        parent: QWidget | None = None,
        caption: str | None = None,
        directory: str | None = None,
    ) -> str: ...

class QHeaderView(QWidget):
    Stretch: int
    ResizeToContents: int

class QAbstractItemView(QWidget):
    SelectRows: Any
    SingleSelection: Any
    NoSelection: Any
    NoEditTriggers: Any

class QSpinBox(QWidget):
    valueChanged: Any
    def setRange(self, minimum: int, maximum: int) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setMinimumWidth(self, width: int) -> None: ...

class QListView(QAbstractItemView):
    doubleClicked: Any
    customContextMenuRequested: Any
    def setModel(self, model: Any) -> None: ...
    def selectionModel(self) -> Any: ...
    def setSelectionMode(self, mode: Any) -> None: ...
    def setContextMenuPolicy(self, policy: int) -> None: ...
    def setCurrentIndex(self, index: Any) -> None: ...

class QListWidgetItem(QObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setData(self, role: int, value: Any) -> None: ...
    def data(self, role: int) -> Any: ...

class QListWidget(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def currentRow(self) -> int: ...
    def setCurrentRow(self, row: int) -> None: ...
    def addItem(self, item: str | QListWidgetItem) -> None: ...
    def item(self, row: int) -> QListWidgetItem | None: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...
    def blockSignals(self, block: bool) -> None: ...
    currentRowChanged: Any

class QAction(QObject):
    triggered: Any

class QMenu(QWidget):
    def addAction(self, text: str) -> QAction: ...

class QStyle:
    SP_MediaStop: int
    SP_MediaPlay: int

class QStatusBar(QWidget):
    def showMessage(self, text: str, timeout: int = ...) -> None: ...
    def addPermanentWidget(self, widget: QWidget) -> None: ...

class QToolBar(QWidget):
    def addAction(self, text: str, slot: Any) -> Any: ...
    def setMovable(self, movable: bool) -> None: ...

class QMainWindow(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setStatusBar(self, status_bar: QStatusBar) -> None: ...
    def statusBar(self) -> QStatusBar: ...
    def addToolBar(self, toolbar: QToolBar) -> None: ...
    def setCentralWidget(self, widget: QWidget) -> None: ...
    def showEvent(self, event: QEvent) -> None: ...
    def resizeEvent(self, event: QEvent) -> None: ...
