from __future__ import annotations

from typing import Any

from .QtCore import QEvent, QObject

class QWidget(QObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def event(self, event: QEvent) -> bool: ...
    def eventFilter(self, obj: QObject, event: QEvent) -> bool: ...
    def closeEvent(self, event: QEvent) -> None: ...
    def setToolTip(self, text: str) -> None: ...
    def setVisible(self, visible: bool) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setFocus(self, reason: int | None = None) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class QApplication(QObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QDialog(QWidget): ...

class QPlainTextEdit(QWidget): ...

class QLabel(QWidget): ...

class QLineEdit(QWidget): ...

class QPushButton(QWidget): ...

class QComboBox(QWidget):
    NoInsert: int
    AdjustToContents: int
    def addItem(self, *args: Any, **kwargs: Any) -> None: ...

class QCheckBox(QWidget): ...

class QAbstractButton(QWidget): ...

class QToolButton(QAbstractButton): ...

class QDialogButtonBox(QWidget):
    Ok: int
    Cancel: int
    Close: int
    ApplyRole: int
    DestructiveRole: int
    AcceptRole: int
    RejectRole: int
    def addButton(self, *args: Any, **kwargs: Any) -> Any: ...

class QMessageBox(QWidget):
    Yes: int
    No: int
    @staticmethod
    def question(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def warning(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def critical(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def information(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...

class QScrollArea(QWidget): ...

class QGroupBox(QWidget): ...

class QFormLayout(QObject):
    AllNonFixedFieldsGrow: int
    ExpandingFieldsGrow: int
    def addRow(self, *args: Any, **kwargs: Any) -> None: ...

class QGridLayout(QObject):
    def addWidget(self, *args: Any, **kwargs: Any) -> None: ...

class QHBoxLayout(QObject):
    def addWidget(self, *args: Any, **kwargs: Any) -> None: ...
    def addLayout(self, *args: Any, **kwargs: Any) -> None: ...

class QVBoxLayout(QHBoxLayout): ...

class QSizePolicy:
    Expanding: int
    Preferred: int
    PreferredType: int
    Fixed: int

class QTableWidget(QWidget): ...

class QTableWidgetItem:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class QTabWidget(QWidget): ...

class QTextEdit(QWidget): ...

class QTextBrowser(QWidget): ...

class QFileDialog(QWidget): ...

class QHeaderView(QWidget):
    Stretch: int
    ResizeToContents: int

class QAbstractItemView(QWidget):
    SelectRows: int
    SingleSelection: int

class QStyle:
    SP_MediaStop: int
