from __future__ import annotations

from typing import Any

from .QtCore import QEvent, QObject

class QWidget(QObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def event(self, event: QEvent) -> bool: ...
    def eventFilter(self, obj: QObject, event: QEvent) -> bool: ...
    def closeEvent(self, event: QEvent) -> None: ...
    def setToolTip(self, text: str) -> None: ...
    def setVisible(self, visible: bool) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setFocus(self, reason: int | None = None) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class QApplication(QObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def setOverrideCursor(cursor: Any) -> None: ...
    @staticmethod
    def restoreOverrideCursor() -> None: ...

class QDialog(QWidget):
    Accepted: int
    Rejected: int
    def exec(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...

class QFrame(QWidget): ...
class QSplitter(QWidget):
    def addWidget(self, widget: QWidget) -> None: ...
    def setObjectName(self, name: str) -> None: ...
    def setStretchFactor(self, index: int, stretch: int) -> None: ...
    def restoreState(self, state: Any) -> None: ...
    def saveState(self) -> Any: ...
    splitterMoved: Any
class QPlainTextEdit(QWidget): ...
class QLabel(QWidget): ...
class QLineEdit(QWidget): ...
class QPushButton(QWidget): ...

class QComboBox(QWidget):
    NoInsert: int
    AdjustToContents: int
    def addItem(self, *args: Any, **kwargs: Any) -> None: ...

class QCheckBox(QWidget): ...
class QAbstractButton(QWidget): ...
class QToolButton(QAbstractButton): ...

class QDialogButtonBox(QWidget):
    Ok: int
    Cancel: int
    Close: int
    ApplyRole: int
    DestructiveRole: int
    AcceptRole: int
    RejectRole: int
    def addButton(self, *args: Any, **kwargs: Any) -> Any: ...

class QMessageBox(QWidget):
    Yes: int
    No: int
    @staticmethod
    def question(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def warning(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def critical(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...
    @staticmethod
    def information(parent: QWidget, title: str, text: str, *args: Any, **kwargs: Any) -> int: ...

class QScrollArea(QWidget): ...
class QGroupBox(QWidget): ...

class QFormLayout(QObject):
    AllNonFixedFieldsGrow: int
    ExpandingFieldsGrow: int
    def addRow(self, *args: Any, **kwargs: Any) -> None: ...

class QGridLayout(QObject):
    def addWidget(self, *args: Any, **kwargs: Any) -> None: ...

class QHBoxLayout(QObject):
    def addWidget(self, *args: Any, **kwargs: Any) -> None: ...
    def addLayout(self, *args: Any, **kwargs: Any) -> None: ...

class QVBoxLayout(QHBoxLayout): ...

class QSizePolicy:
    Expanding: int
    Preferred: int
    PreferredType: int
    Fixed: int

class QTableWidget(QWidget):
    SelectRows: Any
    SingleSelection: Any
    NoEditTriggers: Any
    NoSelection: Any
    def __init__(self, rows: int, columns: int, parent: QWidget | None = None) -> None: ...
    def setSelectionBehavior(self, *args: Any, **kwargs: Any) -> None: ...
    def setSelectionMode(self, *args: Any, **kwargs: Any) -> None: ...
    def setEditTriggers(self, *args: Any, **kwargs: Any) -> None: ...
    def setRowCount(self, count: int) -> None: ...
    def setHorizontalHeaderLabels(self, labels: list[str]) -> None: ...
    def horizontalHeader(self) -> Any: ...
    def verticalHeader(self) -> Any: ...
    def setItem(self, row: int, column: int, item: "QTableWidgetItem") -> None: ...
    def resizeColumnsToContents(self) -> None: ...

class QTableWidgetItem:
    def __init__(self, text: str) -> None: ...

class QTabWidget(QWidget): ...
class QTextEdit(QPlainTextEdit): ...
class QTextBrowser(QWidget): ...

class QFileDialog(QWidget):
    @staticmethod
    def getSaveFileName(*args: Any, **kwargs: Any) -> tuple[str, str]: ...
    @staticmethod
    def getOpenFileName(*args: Any, **kwargs: Any) -> tuple[str, str]: ...

class QHeaderView(QWidget):
    Stretch: int
    ResizeToContents: int

class QAbstractItemView(QWidget):
    SelectRows: Any
    SingleSelection: Any
    NoSelection: Any
    NoEditTriggers: Any

class QListWidgetItem(QObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setData(self, role: int, value: Any) -> None: ...
    def data(self, role: int) -> Any: ...

class QListWidget(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def currentRow(self) -> int: ...
    def setCurrentRow(self, row: int) -> None: ...
    def addItem(self, text: str) -> None: ...
    def item(self, row: int) -> QListWidgetItem | None: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...
    def blockSignals(self, block: bool) -> None: ...
    currentRowChanged: Any

class QStyle:
    SP_MediaStop: int
